name: Build and Push Docker mac

on:
  workflow_dispatch:
  release:
    types: [published]  # This triggers the workflow when a release is published

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: coder007/real_char:latest
